### ISSUE TITLE
Integer overflow in PUCUUTF32Normalize

### ISSUE THREAD

**Issue by andersmelander** [BeRo1985/pucu#7]
The statement...

https://github.com/BeRo1985/pucu/blob/ea0b2a5fc5dbd4669f774442ee2bd88075909618/src/PUCUCode.pas#L3340-L3342

...can cause an integer overflow when the multiplication of two 32-bit numbers overflows 32-bits.

One way to avoid it is to simply promote the numbers to 64-bit like this:

```pascal
CompositionSequenceIndex :=
  PUCUUnicodeCharacterCompositionHashTableData[
    TPUCUUInt32((TPUCUUInt64(StartCodePoint)*98303927) xor (TPUCUUInt64(CodePoint)*24710753)) and
    PUCUUnicodeCharacterCompositionHashTableMask];

```

**Comment by BeRo1985** [comment]
Thank you for reporting this potential bug. However, in this specific case, the integer overflow is actually by design, as it is a part of the algorithm for Hash Tables.

In these tables, hash functions are specifically designed to produce a hash for each key within the given set. In the process of achieving this, integer overflow may occur as a part of the algorithm.

The code snippet you provided uses a technique called "xor-based folding" in which two large prime numbers (in this case, 98303927 and 24710753) are multiplied by the input values (StartCodePoint and CodePoint). The result is then xor'd together, which can cause integer overflow. However, this is expected and necessary for the proper functioning of the Hash Table algorithm.

The overflow is not an issue in this context because the hash table size is smaller than the maximum value of a 32-bit integer, and the result is masked with the PUCUUnicodeCharacterCompositionHashTableMask to ensure that the final value fits within the hash table's range.

Promoting the numbers to 64-bit, as you suggested, might not be necessary in this case, as the algorithm is designed to work with the 32-bit integer overflow. However, if it becomes a concern in the future, your proposed solution could be considered.

**Comment by andersmelander** [comment]
> The overflow is not an issue in this context because the hash table size is smaller than the maximum value of a 32-bit integer

I think you misunderstood me. The problem is not a theoretical one; I _have_ experienced integer overflow exceptions caused by this.

I understand that the masking will ensure that the result of the expression is kept within the bound of the array. That's not the problem.
The problem is that you are multiplying two 32-bit values and that the result of that might overflow 32 bits leading to an exception.

However, I just now noticed that you have disabled overflow checks in the `pucu.pas` source (`{$overflowchecks off}`) which means that the overflow will be ignored and the result truncated to 32 bits.
I got the exception because I needed to tweak the composition algorithm a bit and had copied the function to my own source, where overflowchecks are not disabled.

So, no bug in your code (you might put in a comment documenting the overflow though :-) ).

Here's what I'm using it for btw (and thanks): https://gitlab.com/anders.bo.melander/pascaltype2/-/work_items/29
